name: Update Data

on:
  schedule:
    - cron: '0 6 * * 1' # Lundi √† 6h du matin
  workflow_dispatch: # Permet de lancer manuellement le bouton "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    
    # üö® C'EST LA LIGNE LA PLUS IMPORTANTE
    permissions:
      contents: write

    steps:
      - name: R√©cup√©ration du code
        uses: actions/checkout@v4

      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation des librairies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Lancement du script
        run: python update_data.py

      - name: Sauvegarde des r√©sultats
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Mise √† jour automatique des donn√©es"
          file_pattern: data.json
