name: Debug Data Pipeline

on:
  workflow_dispatch: # Lancement manuel uniquement pour tester

jobs:
  debug-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write # INDISPENSABLE

    steps:
      - name: 1. Récupération du code
        uses: actions/checkout@v4

      - name: 2. Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Installation des librairies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: 4. Lancement du Script d'Audit
        run: python update_data.py

      - name: 5. Sauvegarde et Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Debug Log Update"
          file_pattern: data.json
